'''
Created on 8-aug-2011

@author: duststorm
'''

add=\
'''R0lGODlhFAAUAMZRAGmUNmmVNm2YOG+ZOXKcQXieQXigR3igSX+jNoCjOH2kTX+kSoGlPISnO4So
QYmrQYmsRIutSI2uRZCxSpSzUZi1N5W0Tpa2Tpu3Npa2T5u3PJi2VJm4U5+6PZu5WKC7Opy6V6C8
XKS+QqC9WqW/PqG9YabAYKrCSKbCYqvEQqfCY6jDY6jDZ6nEZKrEZ6rFabDHTa7GXrDIR6/HX6zH
brLJS67Hbq/IcK/Ja7XLU7XMS7LKcLXNdLrRT7vPYLvQWMDVU8DVXsLWWMXZV8XZYsXYfsrdXMvd
Z8nbgsvdcs/iYNDhbtXmZNXlc9rpd9zreeHujv//////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////yH+
EUNyZWF0ZWQgd2l0aCBHSU1QACH5BAEKAH8ALAAAAAAUABQAAAezgH+Cg4SFhoeIiYIHNzY2NwqK
hDRQT09QPJKDL05MTE47moIsTUpKTTiiACVLRkZLLgGIBi0rKypFR0NDR0goti0LhCFJRMZEQkBA
QsdESSaEHkE91NXW1EEjhBs/Ot7f4N4/IIQUPjnoOTUyMjXpOT4chAQZFxcWMTApKTAzFvYZCiAC
EOEECRInJsjSBEHEhw8iJIj646ADBgwdHkxkoKFCBQ0NJgpIgABBggETU6oUFAgAOw==
'''

remove=\
'''R0lGODlhFAAUAIQaAK1AQKtBQdI9PK5IR7xERrxFR71FR71FSNFCRLNLSr1KS9ZFQcJLTcFOTtVL
S8RRUcNUU9VQUsZWVcZaWNpVUctfWt5cVcxkX81lYOFtZ////////////////////////yH+EUNy
ZWF0ZWQgd2l0aCBHSU1QACH5BAEKAB8ALAAAAAAUABQAAAVL4CeOZGmeaKqubOu+sDlgV23fNZaQ
U2b9wOAvUyFBKIukcpmkSEgNh2BKrU4dD5Iiguh6v90IgxQ4GAroAoGQLhgOgJh8Tq/b76IQADs='''