# -*- coding: utf-8 -*-
'''
Translate fields from english to dutch

Created on Jan 7, 2011

@author: kervel
'''

'''Defines fieldnames in english, and their dutch translation'''
vertalingen = {
    "acquisition.date" : "Verwerving: Datum",
    "acquisition.method" : "Verwerving: Methode",
    "acquisition.price.value" : "Aankoopprijs",
    "acquisition.date.precision" : "Verwerving: Nauwkeurigheid Datum",
    "acquisition.price.notes" : "Aankoopprijs: Opmerkingen",
    "acquisition.place" : "Verwerving: Plaats",
    "acquisition.reason": "Verwerving: Reden",
    "acquisition.notes" : "Verwerving: Opmerkingen",
    "acquisition.price.currency" : "Aankoopprijs: Valuta",
    "acquisition.source" : "Verwerving: Van",
    "address.country" : "Adres: Adres",
    "address.country" : "Adres: Land",
    "address.place" : "Adres: Plaats",
    "address.postal_code" : "Adres: Postcode",
    "address.type" : "Adres: Type",
    "address" : "Adres",
    "administration_name" : "Naam administratie",
    "alternative_number" : "Nummer",
    "alternative_number.type" : "Nummer: Soort",
    "association.person" : "Geassocieerde persoon/instelling: Naam",
    "association.person.type" : "Geassocieerde persoon/instelling: Soort naam",
    "broader_term" : "Meer algemene term",
    "collection" : "Collectie",
    "completeness" : "Compleetheid",
    "condition" : "Toestand",
    "condition.part" : "Toestand: Onderdeel",
    "condition.check.name" : "Toestand: Controleur",
    "condition.date" : "Toestand: Datum",
    "condition.notes" : "Toestand: Opmerkingen",
    "contact.name": "Naam contactpersoon",
    "contact.job_title": "Functie contactpersoon",
    "content.description" : "Inhoudsbeschrijving",
    "creator" : "Vervaardiger",
    "creator.role": "Vervaardiger: rol",
    "creator.date_of_birth": "Vervaardiger: Geboortedatum",
    "creator.date_of_death": "Vervaardiger: Sterftedatum",
    "current_owner" : "Huidige eigenaar",
    "description" : "Inhoudelijke beschrijving",
    "description.date" : "Inhoudelijke beschrijving: datum", 
    "description.name" : "Inhoudelijke beschrijving: auteur",
    "dimension.part" : "Afmeting: Onderdeel",
    "dimension.type" : "Afmeting: Afmeting",
    "dimension.unit" : "Afmeting: Eenheid",
    "dimension.value" : "Afmeting: Waarde",
    "documentation.author" : "Documentatie: Auteur",
    "documentation.page_reference" : "Documentatie: Pagina-aanduiding",
    "documentation.title" : "Documentatie: Titel",
    "equivalent_name": "Equivalente naam",
    "exhibition": "Tentoonstelling",
    "exhibition.date.start": "Tentoonstelling: start",
    "exhibition.date.end": "Tentoonstelling: einde",
    "exhibition.organiser": "Tentoonstelling: organisator",
    "exhibition.notes": "Tentoonstelling: opmerkingen",
    "input_by" : "Invoer: Naam",
    "inscription.content" : "Opschriften: Inhoud",
    "inscription.position" : "Opschriften: Positie",
    "inscription.type": "Opschriften: Type",
    "institution.name" : "Instellingsnaam",
    "insurance.value" : "Verzekering: Waarde",
    "insurance.value.currency" : "Verzekering: Valuta",
    "insurance.valuer" : "Verzekering: Taxateur",
    "insurance.date" : "Verzekering: Datum",
    "label.date" : "Label: Datum",
    "label.text" : "Label: Tekst",
    "location" : "Standplaats",
    "location_type" : "Standplaats: Type",
    "location.type" : "Standplaats: Type",
    "location.date.begin" : "Standplaats: Begindatum",
    "location.date.start" : "Standplaats: Begindatum",
    "location.date.end" : "Standplaats: Einddatum",
    "location.default" : "Vaste standplaats",
    "location_check.date" : "Standplaatscontrole: Datum",
    "location_check.name" : "Standplaatscontrole: Controleur",
    "location_normal" : "Vaste standplaats",
    "location_notes" : "Vast standplaats: Bijzonderheden",
    "loan.out.contract.period.start": "Bruikleen: start contract",
    "loan.out.contract.period.end": "Bruikleen: einde contract",
    "loan.out.contract.period.start": "Bruikleen: start contract",
    "loan.out.requester": "Bruikleen: Aangevraagd door",
    "loan.out.requester.contact": "Bruikleen: Contactpersoon",
    "loan.out.request.period.start": "Bruikleen: start aanvraag",
    "loan.out.request.period.end": "Bruikleen: einde aanvraag",
    "loan.out.status": "Bruikleen: status",
    "loan.out.number": "Bruikleen: nummer",
    "material" : "Materiaal",
    "material.notes" : "Materiaal: Opmerkingen",
    "material.part" : "Materiaal: Onderdeel",
    "name" : "Naam",
    "narrower_term" : "Meer specifieke term",
    "name.note" : "Naam: Opmerking",
    "name.type" : "Soort naam",
    "number_of_parts" : "Aantal",
    "notes": "Opmerkingen",
    "object_category" : "Objectcategorie",
    "object_name" : "Objectnaam",
    "object_name.notes" : "Objectnaam: opmerkingen",
    "object_number" : "Objectnummer",
    "owner_hist.owner" : "Eigendomsgeschiedenis: Eigenaar",
    "owner_hist.date.begin" : "Eigendomsgeschiedenis: Datum vanaf",
    "owner_hist.date.end" : "Eigendomsgeschiedenis: Datum tot",
    "part" : "Onderdeel",
    "physical_description" : "Fysieke beschrijving",
    "phone": "Telefoonnummer",
    "preservation_form" : "Bewaarvorm",
    "production.date.end" : "Datering tot",
    "production.date.start" : "Datering van",
    "production.date.end.prec" : "Nauwkerigheid Datering tot",
    "production.date.start.prec" : "Nauwkeurigheid Datering van",
    "production.date.notes" : "Datering: Opmerkingen",
    "production.period" : "Datering: Periode",
    "production.place" : "Vervaardiging: Plaats",
    "related_object.reference" : "Gerelateerd object: verwijzing",
    "related_object.notes" : "Gerelateerd object: opmerkingen",
    "reproduction.identifier_URL" : "Foto Bestandsnaam",
    "reproduction.reference" : "Foto referentie",
    "reproduction.type" : "Foto type",
    "reproduction.date" : "Foto datum",
    "technique" : "Techniek",
    "technique_part" : "Technieken: Onderdeel",
    "term" : "Term",
    "text" : "Tekst",
    "title" : "Titel",
    "title.type" : "Titel: Soort",
    "title.notes" : "Titel: Opmerkingen",
    "use": "Gebruik (voorkeursterm)"
    }

'''Translate given string, which should be a field name,
from english to dutch, if a translation is defined for it.
Tries Changing . to _ and the other way around to find translation
for name. If no translation is found, the original input string
is returned.'''
def tr(x):
    if (x in vertalingen.keys()):
        return vertalingen[x]
    underscorenotation = x.replace(".","_")
    if (underscorenotation in vertalingen.keys()):
        return vertalingen[underscorenotation]
    dotnotation = x.replace("_",".")
    if (dotnotation in vertalingen.keys()):
        return vertalingen[dotnotation]
    return x